services:
  ia_syslog:
    hostname:         ia_syslog.innovanon.com
    build:
      context:        .
      tags:
        - ia_syslog:latest
    restart:          no
    logging:
      driver:         syslog   
