services:
  ia_syslog:
    hostname:         ia_syslog.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_syslog:latest
        -           ia_syslog:latest
        - innovanon/ia_syslog
        -           ia_syslog
    image:            innovanon/ia_syslog
    restart:          no
    logging:
      driver:         syslog   
